---
- hosts: webservers
  become: yes
  tasks:
    - name: Installing apache2 on Debian systems
      apt:
        name: apache2
        state: installed
    - name: Starting apache2 service
      service:
        name: apache2
        state: started
    - name: Coping index.html file
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - name: To restart apache2 service
      service:
        name: apache2
        state: restarted
